size: 50
per_page_categories: 5
per_page_lesson: 10
avatar_size: "100x100"
icon_size: "50x50"
num_my_lessons: 10
per_page_words: 10
per_page_users: 20
number_of_answer: 3
status:
  Learned: learned
  Not_learned: not_learned
  All: all_word
sql:
  word_learned: "id in (select r.word_id 
    from results r join lessons l 
    on r.lesson_id = l.id where l.user_id = ?)"
  word_not_learned: "id not in (select r.word_id 
    from results r join lessons l 
    on r.lesson_id = l.id where l.user_id =? )"
  find_user: "name LIKE ?"
duration:
  30min: 30
  60min: 60
  90min: 90
question_count:
  20question: 20
  40question: 40
  60question: 60
logo_size: "140x40"
word_status:
  alphabet: alphabet
  newest_update: newest_update
  all: all_word
file_format:
  xls: "xls"
  csv: "csv"
